server:
  port: 8010

eureka:
  instance:
    hostname: localhost
  client:
    #\u662F\u5426\u628A\u5F53\u524D\u5BA2\u6237\u7AEF\u6CE8\u518C\u5230Eureka
    registerWithEureka: false
    #
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: eureka-server