server:
  port: 8011

spring:
  application:
    name: feign-client

eureka:
  server:
    hostname: localhost
    port: 8010
  client:
    serviceUrl:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
